version: '3.8'

services:
  api:
    build: .
    container_name: devops-api
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/logs
      - ./backups:/backups
    environment:
      - FLASK_ENV=production
    networks:
      - devops-net
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: devops-web
    ports:
      - "8080:80"
    volumes:
      - ./app/frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - devops-net
    restart: unless-stopped
    depends_on:
      - api

  monitor:
    build: .
    container_name: devops-monitor
    volumes:
      - ./logs:/logs
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        while true; do
          /scripts/check_health.sh https://google.com
          /scripts/check_health.sh https://github.com
          sleep 60
        done
    networks:
      - devops-net
    restart: unless-stopped

networks:
  devops-net:
    driver: bridge

volumes:
  logs:
  backups: